package app.next.udacity.com.nextthing.model;

import java.util.Date;

/**
 * Created by Shaman on 12/29/14.
 */
public class NextThingPO {
    private Integer id;
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thing.description
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thing.title
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thing.vote
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    private Integer vote;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thing.create_time
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thing.modify_time
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thing.id
     * @return  the value of thing.id
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thing.id
     * @param id  the value for thing.id
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thing.url
     * @return  the value of thing.url
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thing.url
     * @param url  the value for thing.url
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thing.description
     * @return  the value of thing.description
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thing.description
     * @param description  the value for thing.description
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thing.title
     * @return  the value of thing.title
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thing.title
     * @param title  the value for thing.title
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thing.vote
     * @return  the value of thing.vote
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public Integer getVote() {
        return vote;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thing.vote
     * @param vote  the value for thing.vote
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public void setVote(Integer vote) {
        this.vote = vote;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thing.create_time
     * @return  the value of thing.create_time
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thing.create_time
     * @param createTime  the value for thing.create_time
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thing.modify_time
     * @return  the value of thing.modify_time
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thing.modify_time
     * @param modifyTime  the value for thing.modify_time
     * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}
